name: Deploy on gh-pages

on:
  push:
    branches:
      - main
          
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup NodeJs 16.x
      uses: actions/setup-node@v1
      with:
          node-version: '16.x'
      
    - name: Install dependencies
      run: npm install
      
    - name: Build
      working-directory: ./angular-hello-world
      run: npm build
      
    - name: Commit and Push new README.md to the repository
      uses: mikeal/publish-to-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'gh-pages'
