name: Deploy on gh-pages
on: 
  push

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        working-directory: ./angular-hello-world
        run: |
          npm ci
          npm run build
          
      - name: Commit and Push 
        run: |
          git fetch
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config http.sslVerify false
          git config user.name "Automated Publisher"
          git config user.email "actions@users.noreply.github.com"
          git remote add publisher "${remote_repo}"
          git show-ref # useful for debugging
          git branch --verbose
          git checkout ${BRANCH_NAME}
          git add ./dist/
          git add ./dist/*
          git commit 
          git push publisher ${BRANCH_NAME}
          
        env:
         BRANCH_NAME: 'gh-pages'
